version: "{branch} {build}"

#build:
#  verbosity: detailed

install:
# - if not exist C:\Users\appveyor\handle mkdir C:\Users\appveyor\handle
# - if not exist C:\Users\appveyor\handle\handle.exe appveyor DownloadFile "https://live.sysinternals.com/handle.exe" -FileName "C:\Users\appveyor\handle\handle.exe"
  - set PATH=%JAVA_HOME%\bin;%PATH%

# To avoid call-selfrun.bat FileNotFound exception, it installs and uses handle.exe as workaround provided by AppVeyor support.
# see http://help.appveyor.com/discussions/problems/5975-the-process-cannot-access-the-file-because-it-is-being-used-by-another-process
#build_script:
#  - C:\Users\appveyor\handle\handle.exe -a -u C:\projects\embulk\embulk-core\build\classes\test\org\embulk\cli\call-selfrun.bat -nobanner
#  - gradlew.bat --info --no-daemon check
#  - script.bat

test_script:
  - script2.bat


cache: []
#  - C:\Users\appveyor\.gradle
#  - C:\Users\appveyor\handle

environment:
  matrix:
  - JAVA_HOME: 'C:\Program Files (x86)\Java\jdk1.7.0\bin'
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10
#  - JAVA_HOME: C:\Program Files\Java\jdk11

#test: off

build: off
deploy: off

matrix:
  fast_finish: true
